### ISSUE TITLE
Missing #include "CUnit/Basic.h"

### ISSUE THREAD

**Issue by lsatenstein** [clibs/sha1#5]
I am using Fedora Linux. 
#include "CUnit/Basic.h" is not in the libraries.

**Comment by tomyhu1995** [comment]
Ubuntu 14.04 has same problem

**Comment by diasbruno** [comment]
You need to install cunit.

**Comment by diasbruno** [comment]
Ubuntu: libcunit1-dev 
Fedora: CUnit CUnit-devel
